version: '3.8'

services:
  postgres-db:
    extends:
      file: docker-compose.yml
      service: postgres-db

  n8n-db:
    extends:
      file: docker-compose.yml
      service: n8n-db

  memory-db:
    extends:
      file: docker-compose.yml
      service: memory-db

  n8n:
    extends:
      file: docker-compose.yml
      service: n8n

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ai_network
    # GPU Configuration for NVIDIA
    deploy:
      resources:
        limits:
          memory: ${OLLAMA_MEMORY_LIMIT:-8G}
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

  open-webui:
    extends:
      file: docker-compose.yml
      service: open-webui

networks:
  ai_network:
    driver: bridge

volumes:
  postgres_data:
  n8n_postgres_data:
  memory_postgres_data:
  n8n_data:
  ollama_data:
  open_webui_data:
